// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/RYL[fic_id]/[chapter_id]/index.tsx";
import * as $1 from "./routes/RYL[fic_id]/feed.tsx";
import * as $2 from "./routes/RYL[fic_id]/index.tsx";
import * as $3 from "./routes/_404.ts";
import * as $4 from "./routes/_500.ts";
import * as $5 from "./routes/_middleware.ts";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/ChapterPlayer.tsx";

const manifest = {
  routes: {
    "./routes/RYL[fic_id]/[chapter_id]/index.tsx": $0,
    "./routes/RYL[fic_id]/feed.tsx": $1,
    "./routes/RYL[fic_id]/index.tsx": $2,
    "./routes/_404.ts": $3,
    "./routes/_500.ts": $4,
    "./routes/_middleware.ts": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/ChapterPlayer.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
