// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/RYL[id].tsx";
import * as $1 from "./routes/_404.ts";
import * as $2 from "./routes/_500.ts";
import * as $3 from "./routes/gtin/resolver.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/scan.tsx";
import * as $$0 from "./islands/Scanner.tsx";

const manifest = {
  routes: {
    "./routes/RYL[id].tsx": $0,
    "./routes/_404.ts": $1,
    "./routes/_500.ts": $2,
    "./routes/gtin/resolver.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/scan.tsx": $5,
  },
  islands: {
    "./islands/Scanner.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
